name: Crystal CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    container:
      image: crystallang/crystal

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: shards install
    - name: Run tests
      run: crystal spec
    - name: Archive tests results
        uses: actions/upload-artifact@v1.0.0
        with:
          name: test-result
          path: tmp/*
